### ISSUE TITLE
css changes

### ISSUE THREAD

**Issue by fabiocaccamo** [Ikimea/ckeditor-light-theme#1]
I was looking for a simple and nice ckeditor theme and I founded your one. **Thanks** :)

Here some overrides that I made to make it looks as below, if you like it feel free to implement the following changes in your theme.

![schermata 2015-11-06 alle 12 40 52](https://cloud.githubusercontent.com/assets/1035294/10996264/d6bc0f96-8483-11e5-9a0d-173a652a02cb.png)

``` css
.cke_inner, .cke_wysiwyg_frame {
    border-top-left-radius: 5px !important;
    border-top-right-radius: 5px !important;
    border-bottom-left-radius: 5px !important;
    border-bottom-right-radius: 5px !important;
}

.cke_top {
    background: #f6f6f6 !important;  
    border-top: none !important;

    border-top-left-radius: 5px !important;
    border-top-right-radius: 5px !important;

    -moz-box-shadow: none !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
}

.cke_bottom {
    background: #f6f6f6 !important;
    border-top: 1px solid #efefef !important;

    border-bottom-left-radius: 5px !important;
    border-bottom-right-radius: 5px !important;
}

.cke_source {
    padding: 13px 15px !important;
    box-sizing: border-box !important;
}

a.cke_button_on {
    -moz-box-shadow: none !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
    background-color: rgba(0,0,0,0.1) !important;
    border-radius: 4px !important;
}
```

PS: **Why don't you submit your theme to the ckeditor team?**
